Try fixing error (still unstable)
Error: Unhandled promise rejection
"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). "